name: Deploy to Production

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to server
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USER }}
        run: |
          # Disable strict host key checking for the deployment
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          
          # Deploy to server
          ssh $USERNAME@$HOST "
            cd /home/matt/corpotismbot &&
            git pull origin main &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            systemctl --user restart corpotismbot
          " 